fail_fast: False

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-yaml
        args: [--allow-multiple-documents, --unsafe] # Use `unsafe` to support GitLab `!reference` tag.
      - id: check-added-large-files
      - id: check-json
      - id: check-symlinks
      - id: check-toml
      - id: destroyed-symlinks
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-case-conflict
      - id: check-merge-conflict

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.4
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix", "--preview"]
      - id: ruff-format
        args: ["--preview"]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: ["--never", "--application-directories=."]
        exclude: "(?:deploy|tests).*"

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        types_or: [python, markdown]

  - repo: https://github.com/python-poetry/poetry
    rev: "1.8.5"
    hooks:
      - id: poetry-check
        files: pyproject.toml

  - repo: https://github.com/crate-ci/typos
    rev: v1.29.0
    hooks:
      - id: typos

  # Source: https://stackoverflow.com/a/75003826/9608133
  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        require_serial: true
        language: system
        types: [python]
        args: ["--install-types", "--non-interactive"]
